### ISSUE TITLE
How would we introduce a few levels of basic instruction that have a related and linear curriculum?

### ISSUE THREAD

**Issue by chrislkeller** [ireapps/pycar#23]
Based on suggestion at [PyCAR 15 feedback thread](https://github.com/ireapps/pycar/issues/17)

@mikejcorey writes:

>There were Pythons part 1-3, but some other sessions also used terms like "intermediate" and "advanced", however, which made it somewhat confusing about where they fit in the progression, and as far as I know they weren't actually related to each other. I would suggest rebranding those as specialized (and highly worthwhile) topics: "Refactoring your code" or "object-oriented Python" and "Python for data analysis."

@esagara writes:

>I feel we need to present python in a way that is easily accessible to new users - i.e. an environment they will be able to easily recognize when launching up python for the first time when they return home. The course should be about learning the language, not setting up a work environment - though I would like to see a separate session on that.
>...
>I like the Python 1, 2, 3, etc. labeling. It makes progression clear and concise. Python for Data Analysis or Object Oriented Python tend to be confusing to people new to programming.
>...
>Eight hours is a lot to tackle in a day. One hour is too short. I would like to see what people think about splitting up the course in chunks of two to four hours over multiple days. This allows both students and instructors to take a break. It would also give us a chance to assign homework where we ask students to look at other sessions - be it in Python or something unrelated. Then we can talk about briefly about how Python applies to those other sessions. This may make it easier to "flip the light switch" so to speak.

**Comment by chrislkeller** [comment]
@esagara raises an awesome point/idea/opportunity...

>an environment they will be able to easily recognize when launching up python for the first time when they return home

**Comment by tommeagher** [comment]
And to be really ambitious, can we map those levels to other tools/languages across the conference?

Is there a level for scraping that's offered in Python, Ruby and JS, or one on aggregating data in SQL, R, Python and Excel?

**Comment by hbillings** [comment]
This touches on something I would love to see NICAR do (and something I'd be willing to help put together, as I've been kicking the idea around for a couple of years now): Intro to Programming Logic. A lot of the basic programming concepts transfer easily across languages. I believe it is totally possible to teach those in pseudocode instead of an actual language, with all of the hassle of system setup and syntax and scary-looking error messages. (My own personal aha moment was during a C++ class in college when I first learned what a loop was, and then realized I'd seen it in PHP and Javascript before.)

Benefits of teaching the logic include not only getting to spend that time on more language-specific training, but also /not needing a hands-on room/. You can talk about theory in front of a lot more people if you don't need each of them in front of a computer (and chances are they'll be paying more attention, too, without the distraction of typing into a terminal).

**Comment by richardsalex** [comment]
As part of having more top-down guidance on classes for various programming languages, I think we've addressed this somewhat. Classes tend to address similar concepts across languages (where applicable) — collection, analysis, viz, etc. In the past, people used to pitch sessions and we'd end up with variations of similar classes. If progressions existed, it wasn't always clear to attendees. We're still working out kinks on naming conventions for classes in Denver, but look for those to be more clear as well.
