### ISSUE TITLE
project2: What does "**" mean?

### ISSUE THREAD

**Issue by jtmx** [ireapps/pycar#24]
Missed the conference and following the tutorial at home.

95: ` merged_data.append(dict(dict1[key], **dict2[key]))`: what does the "**" mean? The comment in the file notes that "**" expands the values - not sure what 'expand' means here.

StackOverflow notes that "**" indicates extra arguments may or may not be used. Not sure if that note applies to this context and if so, what extra arguments we may be referring to.

**Comment by tommeagher** [comment]
That part of the day was designed by @hbillings, so Heather, would you like to take a swing at explaining the ** dict unpacking for Jenny?

**Comment by hbillings** [comment]
Oof, sorry about the late response on this! Also...oh man, reading my own code sucks. Let me try to remember what I was doing there...

So this is an example of `kwargs`, which stands for "keyword arguments." If you look at line 15, you'll see I'm doing this there:
``deets_plus_job = dict(my_deets, **{'employer': 'Northwestern University', 'boss': 'Joe Germuska'})``

Alternately, I could write this in the same way I wrote what's on line 13:
``deets_plus_job = dict(my_deets, 'employer' = 'Northwestern University', 'boss'='Joe Germuska')``

You can see from that example that the double asterisks mean, "Take whatever is in this dictionary, and add it to the first dictionary."

The helpful part about this technique (which is called "unpacking") comes about when you're writing code that is going to have to deal with either a lot of values or a variable number of values. So let's go back to the original line: 

``merged_data.append(dict(dict1[key], **dict2[key]))``

`dict1`, IIRC, is a dict of dicts, meaning that `dict1[key]` is itself a dict. If memory serves, both `dict1` and dict2` are dicts of player details, but each one has different information. They share a common key: the player ID. So we want to join them together based on that ID.

The line in question finds the dict that corresponds to `dict1[key]`, set that as the key, and then unpack or expand the values of the second dict so that they can be added.

There is perhaps a more clear explanation with examples on how unpacking works here: http://programmers.stackexchange.com/a/131415

**Comment by jtmx** [comment]
Thanks Heather. Unpacking makes much more sense now - a short cut for adding dicts together so you don't have to rewrite the entire thing. Many thanks.
