### ISSUE TITLE
2 vs. 3

### ISSUE THREAD

**Issue by scott2b** [ireapps/pycar#30]
I feel like there should be some early coverage on Python 2 vs. Python 3. This is generally a source of confusion for newcomers. People tend to interpret higher numbers to mean latest version, and when it comes to major versions in particular, they tend to want to grab the latest and greatest.

I think there is a tendency by outsiders to perceive the ongoing run of parallel development to be some kind of debacle or rift in the community. I like to underscore the fact that it is quite the opposite, and that the conservativeness by which Python has made this transition is really one of the great things about the Python community. It seems like every time I try to do something with Ruby or Node, to name a couple of examples from personal experience, I have to have the latest and greatest of everything. Some development communities seem to have this driving need to continuously push the technology forward. I find I experience much less of this with Python, while it still manages to stay vibrant and growing and current.

Also, I have not scrutinized the code enough to know for sure, but I wonder if it would be a stretch for the code examples to all be both 2 and 3 compatible. I think this would mostly depend on external dependencies. If it can be done, it might prevent some headache as there are bound to be attendees who have already installed 3 before the workshop. Of course there is a teaching opportunity in running different versions side by side, but I feel like that falls a bit out of scope for what we are doing here.

**Comment by richardsalex** [comment]
Hey, @scott2b, to your point about attendees already having 3 installed — we get around this by having them use lab computers in Denver instead of their own machines. We've gone back and forth on this a bit, and I think the consensus is we'd rather have attendees spend time learning the basics and working on some projects that puzzling out inscrutable install errors. For that, we're working on an "open lab," where conference attendees can come and get help from experienced folks outside of the classroom.

I do think it's important to outline for them what you've described: that 2 is not somehow inferior to 3, just different. 

Re: compatibility between the two, not sure if that's something we'd necessarily have time to tackle before the workshop, but I'm going to withhold judgement until I see @tommeagher's repo reorg. I think the big roadblock would be how the two deal with encoding differently, but I'm honestly not that well-versed in 3.

**Comment by tommeagher** [comment]
@scott2b, thanks for raising this issue. I agree we'll want to discuss the differences between the versions briefly during the session. I'd love to push this toward being all Python 3, particularly for how it handles unicode, but I don't know if we'll have time to do that before the conference this year. If you, or anyone else on the team has the bandwidth over the next couple weeks to make it fully compatible with 3, that'd be amazing. 
Otherwise, I'd say moving all of the lessons to Python 3 is a high priority for next year.

**Comment by tommeagher** [comment]
Now that we're past NICAR, I'll try to carve out a little time to make a branch to port the code to Python3.

**Comment by tommeagher** [comment]
So somehow 11 months have flown by. I'd still like us to move ahead and move to Python 3 this year. Would anyone in our squad of instructors for Jacksonville be able to help port the exercises and documentation to 3?

**Comment by tommeagher** [comment]
I'll take this on. I've started a [branch here](https://github.com/ireapps/pycar/tree/py3) that thus far just has a notebook for the basics section. I'll keep adding tot his branch over the next few days and then will ask for volunteers to give it a look.

**Comment by robroc** [comment]
Sorry I've been silent so long. Crazy few weeks. I can start contributing more actively. @tommeagher, anything in particular you need help with?

**Comment by zufanka** [comment]
Second project is already in 3 !

**Comment by tommeagher** [comment]
@robroc no problem. I've done the basics and project 1 and @zufanka has done project 2. Give me another day or so to finish porting project 3. Then I could use your help testing and checking everything and offering feedback on improvements. I'll holler when I'm ready.

**Comment by tommeagher** [comment]
Closed by 123e83bdf530b2cc067bd24e748894f7108316e2
