### ISSUE TITLE
project 3 workflow

### ISSUE THREAD

**Issue by scott2b** [ireapps/pycar#35]
Ok, reiterating my question about project 3, hopefully in the right repository this time.

Is it the case that the file scraper.py is meant to be the working file for the narrative outlined in the README? So the idea would be to work through the Readme in that file? Or is the Readme meant to be explained via the shell and then get_json and json_to_csv (and scraper?) done in files?

**Comment by tommeagher** [comment]
I'm not sure I understand your question exactly, but I'll try, and maybe @esagara can elaborate and correct what I get wrong.

The idea is to start with scraper.py and have the class fill in the blanks with you (the working version of the script is in ```completed/scraper_complete.py```) as you explain the process of web scraping and build on the lessons earlier in the day. As much possible, you want to get them to work on pieces on their own rather than just transcribing what you tell them to. By this point in the day, for each of these scripts, we should be writing in the files and then running the script from the command line rather than in the interactive interpreter).

That generally should map to the README down to the section that begins "Dealing with JSON from the web". The README is more intended to be a reference once you get back to your newsroom, or for those following along from home (and for the instructors). Wherever you see errors or spots for improvement, pull requests are gladly accepted. 

After scraper.py, you want to tackle get_json.py and then json_to_csv.py. Again, the working versions of those scripts are in the completed/ dir, but the intent is to have the students fill in the code below each line of comments in the file. 

Does that help?

**Comment by scott2b** [comment]
Yes, perfect. Thanks.

**Comment by tommeagher** [comment]
Great. Sorry for any confusion. With a project like this, where we have about a dozen contributors who only look at pieces of this once a year before the conference, there are definitely bumps that can be smoothed out. So please let us know ways you see to improve the flow or the code. Any advice from a pair of fresh eyes is greatly appreciated.
