### ISSUE TITLE
BeautifulSoup4 may need to be upgraded

### ISSUE THREAD

**Issue by esagara** [ireapps/pycar#44]
I just tried bootstrapping the pycar repo using ```pip install -r requirements.txt```. When importing BeautifulSoup it throws an error - ```ImportError: cannot import name 'HTMLParseError'```. This is fixed by running ```pip install --upgrade beautifulsoup4```. Apparently this has been an [issue](http://stackoverflow.com/questions/28745153/importing-bs4-in-python-3-5) since Python 3.5. Do we need to update requirements.txt?

**Comment by tommeagher** [comment]
I'm assuming you used ```pip3 install beautifulsoup4```? 

I haven't had that issue, but if it's common, we should address it. Do you want to update requirements.txt? 

It shouldn't be a problem in the class, since it's already installed on the machines, but will be good for the repo to work for folks when they get home.

**Comment by esagara** [comment]
I've been using pyenv to manage my python versions, so I did not need the pip3 command. Is there a reason for the version requirement? I don't want to alter it and break something down the road.

**Comment by rdmurphy** [comment]
`pip3` (and `python3`) are where Python 3 lives in scenarios where both versions have been installed. Main reason is to avoid breaking all the things where `python` is expected to be v2 in build chains. Dunno what computers y'all are using, but I know this is the case with Homebrew and MacOS.

If you use something like `pyenv` or `virtualenv` to create a Python 3 environment, it'll point `pip` at `pip3` (and `python` at `python3`) for you because you've safely left the land of "system" Python.
